# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 434)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.runSimulation = QtWidgets.QPushButton(self.centralwidget)
        self.runSimulation.setGeometry(QtCore.QRect(450, 390, 111, 31))
        self.runSimulation.setObjectName("runSimulation")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(110, 0, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.disasterSelection = QtWidgets.QComboBox(self.centralwidget)
        self.disasterSelection.setGeometry(QtCore.QRect(360, 120, 111, 21))
        self.disasterSelection.setObjectName("disasterSelection")
        self.disasterSelection.addItem("")
        self.disasterSelection.addItem("")
        self.disasterSelection.addItem("")
        self.disasterSelectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.disasterSelectionLabel.setGeometry(QtCore.QRect(10, 110, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.disasterSelectionLabel.setFont(font)
        self.disasterSelectionLabel.setObjectName("disasterSelectionLabel")
        self.edgesLabel = QtWidgets.QLabel(self.centralwidget)
        self.edgesLabel.setGeometry(QtCore.QRect(10, 150, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edgesLabel.setFont(font)
        self.edgesLabel.setObjectName("edgesLabel")
        self.edgesBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.edgesBrowse.setGeometry(QtCore.QRect(200, 160, 75, 23))
        self.edgesBrowse.setObjectName("edgesBrowse")
        self.nodesBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.nodesBrowse.setGeometry(QtCore.QRect(200, 200, 75, 23))
        self.nodesBrowse.setObjectName("nodesBrowse")
        self.nodesLabel = QtWidgets.QLabel(self.centralwidget)
        self.nodesLabel.setGeometry(QtCore.QRect(10, 190, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nodesLabel.setFont(font)
        self.nodesLabel.setObjectName("nodesLabel")
        self.modelsBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.modelsBrowse.setGeometry(QtCore.QRect(350, 240, 75, 23))
        self.modelsBrowse.setObjectName("modelsBrowse")
        self.directoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.directoryLabel.setGeometry(QtCore.QRect(10, 230, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.directoryLabel.setFont(font)
        self.directoryLabel.setObjectName("directoryLabel")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("icon-circle.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.autorunCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.autorunCheck.setGeometry(QtCore.QRect(0, 270, 251, 31))
        self.autorunCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.autorunCheck.setObjectName("autorunCheck")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.runSimulation.setText(_translate("MainWindow", "Run Simulation"))
        self.title.setText(_translate("MainWindow", "EvacSim"))
        self.disasterSelection.setCurrentText(_translate("MainWindow", "Earthquake"))
        self.disasterSelection.setItemText(0, _translate("MainWindow", "Earthquake"))
        self.disasterSelection.setItemText(1, _translate("MainWindow", "Tsunami"))
        self.disasterSelection.setItemText(2, _translate("MainWindow", "Hurricane"))
        self.disasterSelectionLabel.setText(_translate("MainWindow", "What type of disaster do you want to simulate?"))
        self.edgesLabel.setText(_translate("MainWindow", "Select your edges.csv file"))
        self.edgesBrowse.setText(_translate("MainWindow", "Browse"))
        self.nodesBrowse.setText(_translate("MainWindow", "Browse"))
        self.nodesLabel.setText(_translate("MainWindow", "Select your nodes.csv file"))
        self.modelsBrowse.setText(_translate("MainWindow", "Browse"))
        self.directoryLabel.setText(_translate("MainWindow", "Select the directory where models are located"))
        self.autorunCheck.setText(_translate("MainWindow", "Open Google Earth Pro on sucessful simulation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
