# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 884)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(110, 0, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(38)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("icon-circle.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1140, 840, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.icon_2 = QtWidgets.QLabel(self.centralwidget)
        self.icon_2.setGeometry(QtCore.QRect(40, 120, 1201, 701))
        self.icon_2.setText("")
        self.icon_2.setPixmap(QtGui.QPixmap("map.PNG"))
        self.icon_2.setScaledContents(True)
        self.icon_2.setObjectName("icon_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "EvacSim"))
        self.pushButton.setText(_translate("MainWindow", "Rerun Simulation"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
